# Generated by Django 3.0.14 on 2021-05-13 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210509_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subgenre',
            field=models.CharField(choices=[('Action', 'Action'), ('Fantasy', 'Fantasy'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Sci-Fi', 'Sci-Fi'), ('Thriller ', 'Thriller'), ('Western', 'Western'), ('War', 'War')], default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Fantasy', 'Fantasy'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Sci-Fi', 'Sci-Fi'), ('Thriller ', 'Thriller'), ('Western', 'Western'), ('War', 'War')], max_length=35),
        ),
        migrations.AlterField(
            model_name='movie',
            name='typ',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV Series', 'TV Series')], max_length=35),
        ),
    ]
