# Generated by Django 3.0.14 on 2021-05-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210513_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='subgenre',
        ),
    ]
