# Generated by Django 3.0.14 on 2021-05-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='averageRating',
            new_name='rating',
        ),
    ]
