# Generated by Django 3.2.3 on 2021-05-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
