# Generated by Django 3.2.3 on 2021-05-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='creators',
        ),
    ]
