# Generated by Django 3.2.3 on 2021-05-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
