# Generated by Django 3.2.3 on 2021-05-15 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
